import {storefront} from './src/shop-view.mjs';
import {imageVariants} from './src/image-assets.mjs';
import fs from 'node:fs';
import vm from 'node:vm';
import crypto from 'node:crypto';
const fontLoading=fs.readFileSync('src/font-loading.js','utf8');
const dict=JSON.parse(fs.readFileSync('src/locales.json','utf8'));
const t=key=>dict.ka[key]||key;
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tr=(key,tag='span',attrs='')=>`<${tag} data-i18n="${key}" ${attrs}>${esc(t(key))}</${tag}>`;
const read=name=>fs.readFileSync('src/'+name+'.html','utf8');
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync('dist/content.js','utf8'),sandbox);
const {dishes,cuts}=sandbox.window.MEATCO_CONTENT;
const runtimeImageVariants=Object.fromEntries(cuts.filter(c=>c.image&&c.photoStatus!=='pending').map(c=>{const v=imageVariants(c.image);return [c.image,v?{src:v.src,width:v.width}:null];}));
const arrow='<span aria-hidden="true">↗</span>';
const localLink=(href,key,cls='')=>`<a class="${cls}" data-local href="${href}">${tr(key)}${cls?arrow:''}</a>`;
const wa=`href="https://wa.me/995568258118" target="_blank" rel="noopener noreferrer"`;
function dishCard(d){return `<article class="dish-card" data-dish-id="${d.id}"><button type="button" class="dish-image" data-open-dish="${d.id}" aria-label="${esc(d.ka[0]+': '+t('dishView'))}"><img src="${d.image}" srcset="${d.image.replace('.webp','-small.webp')} 480w, ${d.image} 960w" sizes="(max-width:620px) 100vw, (max-width:1000px) 50vw, 33vw" width="960" height="640" alt="${esc(d.ka[0])}" loading="lazy" fetchpriority="low" decoding="async"></button><div class="dish-body"><p class="dish-meta">${esc(t(d.category))}<span aria-hidden="true"> · </span>${esc(t(d.method))}</p><h3>${esc(d.ka[0])}</h3><p class="dish-description">${esc(d.ka[1])}</p><button class="dish-cta" type="button" data-open-dish="${d.id}">${tr('dishView')}${arrow}</button></div></article>`;}
function dishDialog(){return `<dialog id="dish-dialog" class="dish-dialog" aria-labelledby="dish-title"><button class="dialog-close" type="button" data-close data-aria="close" aria-label="${esc(t('close'))}">×</button><figure><img id="dish-detail-image" src="${dishes[0].image}" alt="${esc(dishes[0].ka[0])}" width="960" height="640" loading="lazy" fetchpriority="low" decoding="async"><figcaption data-i18n="dishPhotoNote">${esc(t('dishPhotoNote'))}</figcaption></figure><div class="dish-detail-copy"><p class="eyebrow" id="dish-detail-meta"></p><h2 id="dish-title">${esc(dishes[0].ka[0])}</h2><p id="dish-description"></p><div class="dish-recommendation">${tr('dishCutsLabel','h3')}<p id="dish-advice"></p><ul id="dish-cut-list"></ul></div><label for="dish-people" data-i18n="dishPeople">${esc(t('dishPeople'))}</label><select id="dish-people"><option value="" data-i18n="peopleUnknown">${esc(t('peopleUnknown'))}</option>${[2,3,4,5,6,8,10,12].map(n=>`<option value="${n}">${n}</option>`).join('')}</select>${tr('dishRawNote','p','class="dish-raw-note"')}<button class="button primary" type="button" id="dish-order">${tr('dishOrder')}${arrow}</button></div></dialog>`;}
function heading(key,intro){return `<div class="container page-heading"><nav class="breadcrumb" aria-label="MeatCO">${localLink('./index.html','home')}<span aria-hidden="true">/</span>${tr(key==='catalogPageHeading'?'navCatalog':'navDishes')}</nav>${tr(key,'h1')}${tr(intro,'p')}</div>`;}
const deliveryRibbon=`<aside class="delivery-ribbon container"><div>${tr('zones','strong')}${tr('deliveryText','p')}</div><button class="text-button" type="button" data-order="any">${tr('checkAddress')}${arrow}</button></aside>`;
function faq(){return `<section class="faq-section" id="faq"><div class="container faq-layout">${tr('faqTitle','h2')}<div class="faqs">${[1,3,7,8,4].map(n=>`<details>${tr('faq'+n+'Q','summary')}${tr('faq'+n+'A','p')}</details>`).join('')}</div></div></section>`;}
function dishPage(){return heading('dishesHeading','dishesIntro')+`<section class="container dishes-browser"><div class="dish-filters"><div class="search-field"><label for="dish-search" data-i18n="searchDish">${esc(t('searchDish'))}</label><div><input type="search" id="dish-search" data-placeholder="searchPlaceholder" placeholder="${esc(t('searchPlaceholder'))}" maxlength="100" autocomplete="off"><button type="button" id="clear-search" data-aria="clearSearch" aria-label="${esc(t('clearSearch'))}" hidden>×</button></div></div><div class="method-field"><label for="dish-method" data-i18n="methodLabel">${esc(t('methodLabel'))}</label><select id="dish-method"><option value="" data-i18n="methodAll">${esc(t('methodAll'))}</option>${['pan','stew','boil','grill','roast','cold'].map(m=>`<option value="${m}" data-i18n="${m}">${esc(t(m))}</option>`).join('')}</select></div></div><div class="filter-bar"><div class="filter-chips" role="group" data-aria="meatType" aria-label="${esc(t('meatType'))}">${['all','pork','beef','offal'].map((cat,i)=>`<button type="button" data-meat-filter="${cat}" aria-pressed="${i===0}">${tr(cat)}</button>`).join('')}</div><p id="dish-count" role="status">${esc(t('dishCount').replace('{n}',15))}</p></div><div class="dish-grid" id="all-dishes">${dishes.map(dishCard).join('')}</div><div id="dish-empty" hidden>${tr('dishNoResults','h2')}${tr('dishNoResultsText','p')}<button type="button" class="text-button" id="reset-filters">${tr('resetFilters')}${arrow}</button><button type="button" class="button primary" data-order="any">${tr('needHelp')}</button></div></section>`+deliveryRibbon;}
const v4=storefront({tr,t,esc,localLink,wa,arrow,cuts,faq});
const pages={home:['index.html',v4.home,'title','description'],catalog:['catalog.html',v4.catalog,'catalogPageTitle','catalogPageDescription'],dishes:['dishes.html',dishPage,'dishesPageTitle','dishesPageDescription']};
for(const [page,[file,render,title,description]] of Object.entries(pages)){
 let html=`<!doctype html>\n<html lang="ka"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><meta name="theme-color" content="#F4EFE6"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><link rel="manifest" href="./manifest.webmanifest"><meta name="robots" content="index,follow"><title>${esc(t(title))}</title><meta name="description" content="${esc(t(description))}"><link rel="icon" href="./assets/brand/meatco-icon-64.png" type="image/png"><link rel="apple-touch-icon" href="./assets/brand/meatco-icon-192.png">${page==='home'?v4.imagePreload():''}<script>${fontLoading.replace('__ENTRY_PAGE__',JSON.stringify(page))}</script><link rel="stylesheet" href="./fonts.css"><link rel="stylesheet" href="./style.css"><link rel="stylesheet" href="./app-ui.css"><link rel="stylesheet" href="./app-shell.css"><script src="./config.js" defer></script><script src="./content.js" defer></script><script src="./app.js" defer></script></head><body data-page="${page}">${v4.header(page)}<main id="main">${render()}</main>${v4.footer()}${read('order-dialogs')}${read('cart-dialogs')}${dishDialog()}<noscript><p class="no-script">MeatCO · WhatsApp: <a href="https://wa.me/995568258118">+995 568 258 118</a>. ქართული / Русский / English.</p></noscript></body></html>`;
 const publicUrl='https://axperik777.github.io/meatco-tbilisi/'+(file==='index.html'?'':file);
 html=html.replace('</head>',`<link rel="canonical" href="${publicUrl}"><meta property="og:type" content="website"><meta property="og:site_name" content="MeatCO"><meta property="og:title" content="${esc(t(title))}"><meta property="og:description" content="${esc(t(description))}"><meta property="og:url" content="${publicUrl}"><meta property="og:image" content="https://axperik777.github.io/meatco-tbilisi/assets/products/beef-tenderloin.webp"><meta name="twitter:card" content="summary_large_image"></head>`);
 html=html.replace('<label><input type="radio" name="meat" value="any" checked>', ['poultry','lamb','veal'].map(c=>`<label data-secondary-type="${c}" hidden><input type="radio" name="meat" value="${c}">${tr(c)}</label>`).join('')+'<label><input type="radio" name="meat" value="any" checked>');
 html=html.replace(/(<([a-z0-9]+)\b[^>]*data-i18n="([^"]+)"[^>]*>)([^<]*)(<\/\2>)/g,(m,start,tag,key,old,end)=>start+esc(t(key))+end);
 fs.writeFileSync('dist/'+file,html+'\n');
}
fs.writeFileSync('dist/app.js',"'use strict';\n(()=>{\nconst strings = "+JSON.stringify(dict,null,2)+";\nconst imageVariants = "+JSON.stringify(runtimeImageVariants)+";\n"+fs.readFileSync('src/product-search.js','utf8')+"\n"+fs.readFileSync('src/app-core.js','utf8').replace('// CART_MODULE',fs.readFileSync('src/cart-core.js','utf8')+'\n'+fs.readFileSync('src/app-shell.js','utf8'))+"\n})();\n");
for(const [file] of Object.values(pages)){
 const html=fs.readFileSync('dist/'+file,'utf8').replace(/(src|href)="\.\/([^"?]+\.(?:js|css))"/g,(match,attr,asset)=>{
  const hash=crypto.createHash('sha256').update(fs.readFileSync('dist/'+asset,'utf8').replace(/\r\n/g,'\n')).digest('hex').slice(0,10);
  return `${attr}="./${asset}?v=${hash}"`;
 });
 fs.writeFileSync('dist/'+file,html);
}
console.log('Built 3 pages with shared content and 3 locales.');
