import fs from 'node:fs';
import vm from 'node:vm';
const dict=JSON.parse(fs.readFileSync('src/locales.json','utf8'));
const t=key=>dict.ka[key]||key;
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tr=(key,tag='span',attrs='')=>`<${tag} data-i18n="${key}" ${attrs}>${esc(t(key))}</${tag}>`;
const read=name=>fs.readFileSync('src/'+name+'.html','utf8');
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync('dist/content.js','utf8'),sandbox);
const {dishes,cuts}=sandbox.window.MEATCO_CONTENT;
const categoryImages={pork:'./assets/meatco-pork-v01.jpg',beef:'./assets/meatco-beef-v01.jpg',offal:'./assets/meatco-offal-v03.webp'};
const arrow='<span aria-hidden="true">↗</span>';
const localLink=(href,key,cls='')=>`<a class="${cls}" data-local href="${href}">${tr(key)}${cls?arrow:''}</a>`;
const wa=`href="https://wa.me/995568258118" target="_blank" rel="noopener noreferrer"`;
const navItems=[['./index.html','navHome','home'],['./catalog.html','navCatalog','catalog'],['./dishes.html','navDishes','dishes'],['./index.html#delivery','navDelivery','delivery'],['./index.html#restaurants','navB2b','b2b']];
function nav(page){return navItems.map(([href,key,id])=>`<a data-local href="${href}" ${id===page?'aria-current="page"':''}>${tr(key)}</a>`).join('');}
function header(page){return `<a class="skip" href="#main">${tr('skip')}</a><header class="header"><div class="container header-inner"><a class="wordmark" data-local href="./index.html" aria-label="MeatCO">MeatCO</a><nav class="desktop-nav" data-aria="navLabel" aria-label="${esc(t('navLabel'))}">${nav(page)}</nav><div class="header-actions"><div class="languages" role="group" data-aria="languageLabel" aria-label="${esc(t('languageLabel'))}"><button type="button" data-lang="ka" aria-label="ქართული" aria-pressed="true">ქარ</button><button type="button" data-lang="ru" aria-label="Русский" aria-pressed="false">RU</button><button type="button" data-lang="en" aria-label="English" aria-pressed="false">EN</button></div><a class="header-wa" data-whatsapp ${wa}>WhatsApp ${arrow}</a><button type="button" class="menu-toggle" id="menu-toggle" aria-expanded="false" aria-controls="mobile-nav" data-aria="menu" aria-label="${esc(t('menu'))}"><span></span><span></span></button></div></div><nav id="mobile-nav" class="mobile-nav container" hidden data-aria="navLabel" aria-label="${esc(t('navLabel'))}">${nav(page)}</nav></header>`;}
function footer(){return `<footer><div class="container footer-shop"><div class="footer-brand"><a class="wordmark" data-local href="./index.html" aria-label="MeatCO">MeatCO</a>${tr('footerTag','p')}</div><div>${tr('footerCatalog','strong')}${localLink('./catalog.html?category=pork','pork')}${localLink('./catalog.html?category=beef','beef')}${localLink('./catalog.html?category=offal','offal')}${localLink('./dishes.html','navDishes')}</div><div>${tr('footerOrder','strong')}${localLink('./index.html#delivery','deliveryTerms')}${localLink('./index.html#restaurants','navB2b')}<a href="tel:+995568258118">+995 568 258 118</a><a data-whatsapp ${wa}>WhatsApp ↗</a></div></div><div class="container footer-bottom"><span>© <span id="year">2026</span> MeatCO</span>${tr('photoNote')}<button type="button" id="privacy-open" data-i18n="privacy">${esc(t('privacy'))}</button></div></footer><div class="mobile-bar">${tr('mobileLabel')}<a class="button primary" data-whatsapp ${wa}>WhatsApp ${arrow}</a></div>`;}
function dishCard(d){return `<article class="dish-card" data-dish-id="${d.id}"><button type="button" class="dish-image" data-open-dish="${d.id}" aria-label="${esc(d.ka[0]+': '+t('dishView'))}"><img src="${d.image}" srcset="${d.image.replace('.webp','-small.webp')} 480w, ${d.image} 960w" sizes="(max-width:620px) 100vw, (max-width:1000px) 50vw, 33vw" width="960" height="640" alt="${esc(d.ka[0])}" loading="lazy"></button><div class="dish-body"><p class="dish-meta">${esc(t(d.category))}<span aria-hidden="true"> · </span>${esc(t(d.method))}</p><h3>${esc(d.ka[0])}</h3><p class="dish-description">${esc(d.ka[1])}</p><button class="dish-cta" type="button" data-open-dish="${d.id}">${tr('dishView')}${arrow}</button></div></article>`;}
function dishDialog(){return `<dialog id="dish-dialog" class="dish-dialog" aria-labelledby="dish-title"><button class="dialog-close" type="button" data-close data-aria="close" aria-label="${esc(t('close'))}">×</button><figure><img id="dish-detail-image" src="${dishes[0].image}" alt="${esc(dishes[0].ka[0])}" width="960" height="640" loading="lazy"><figcaption data-i18n="dishPhotoNote">${esc(t('dishPhotoNote'))}</figcaption></figure><div class="dish-detail-copy"><p class="eyebrow" id="dish-detail-meta"></p><h2 id="dish-title">${esc(dishes[0].ka[0])}</h2><p id="dish-description"></p><div class="dish-recommendation">${tr('dishCutsLabel','h3')}<p id="dish-advice"></p><ul id="dish-cut-list"></ul></div><label for="dish-people" data-i18n="dishPeople">${esc(t('dishPeople'))}</label><select id="dish-people"><option value="" data-i18n="peopleUnknown">${esc(t('peopleUnknown'))}</option>${[2,3,4,5,6,8,10,12].map(n=>`<option value="${n}">${n}</option>`).join('')}</select>${tr('dishRawNote','p','class="dish-raw-note"')}<button class="button primary" type="button" id="dish-order">${tr('dishOrder')}${arrow}</button></div></dialog>`;}
function heading(key,intro){return `<div class="container page-heading"><nav class="breadcrumb" aria-label="MeatCO">${localLink('./index.html','home')}<span aria-hidden="true">/</span>${tr(key==='catalogPageHeading'?'navCatalog':'navDishes')}</nav>${tr(key,'h1')}${tr(intro,'p')}</div>`;}
const deliveryRibbon=`<aside class="delivery-ribbon container"><div>${tr('zones','strong')}${tr('deliveryText','p')}</div><button class="text-button" type="button" data-order="any">${tr('checkAddress')}${arrow}</button></aside>`;
function categories(){return `<section class="container section" id="catalog"><div class="section-heading"><div>${tr('navCatalog','p','class="eyebrow"')}${tr('catalogHomeTitle','h2')}</div>${tr('catalogHomeIntro','p')}</div><div class="category-grid">${['pork','beef','offal'].map(cat=>`<a class="category-card" data-local href="./catalog.html?category=${cat}"><div class="category-photo"><img src="${categoryImages[cat]}" width="1000" height="750" loading="lazy" data-alt="${cat}Alt" alt="${esc(t(cat+'Alt'))}"></div><div class="category-copy">${tr(cat,'h3')}${tr('category'+cat[0].toUpperCase()+cat.slice(1)+'Intro','p')}<span class="category-link">${tr('browseCuts')}${arrow}</span></div></a>`).join('')}</div></section>`;}
function methodGuide(){return `<section class="container method-section"><div>${tr('methodGuideTitle','h2')}${tr('methodGuideIntro','p')}</div><div class="method-links">${[['grill','methodGrillText'],['stew','methodStewText'],['cold','methodColdText'],['boil','methodBoilText']].map(([method,key])=>`<a data-local href="./dishes.html?method=${method}">${tr(method,'strong')}${tr(key,'span')}${arrow}</a>`).join('')}</div></section>`;}
function faq(){return `<section class="faq-section" id="faq"><div class="container faq-layout">${tr('faqTitle','h2')}<div class="faqs">${[1,3,7,8,4,5].map(n=>`<details>${tr('faq'+n+'Q','summary')}${tr('faq'+n+'A','p')}</details>`).join('')}</div></div></section>`;}
function home(){const intro=read('home-intro').replace('href="#catalog"','href="./catalog.html" data-local');return intro+categories()+`<section class="home-dishes container section" id="meal-guide"><div class="section-heading"><div>${tr('featured','p','class="eyebrow"')}${tr('dishesTeaser','h2')}</div>${localLink('./dishes.html','allDishes','text-button')}</div>${tr('dishesIntro','p','class="section-intro"')}<div class="dish-grid" id="featured-dishes">${dishes.slice(0,6).map(dishCard).join('')}</div></section>`+methodGuide()+read('home-extras')+read('home-delivery')+faq();}
function catalog(){return heading('catalogPageHeading','catalogPageIntro')+`<section class="container catalog-browser"><div class="filter-chips catalog-tabs" role="group" data-aria="navCatalog" aria-label="${esc(t('navCatalog'))}">${['pork','beef','offal'].map((cat,i)=>`<button type="button" data-category="${cat}" aria-pressed="${i===0}">${tr(cat)}</button>`).join('')}</div><div class="cut-layout"><figure class="cut-photo"><img id="catalog-image" src="${categoryImages.pork}" width="1000" height="750" alt="${esc(t('porkAlt'))}"><figcaption data-i18n="catalogCaption">${esc(t('catalogCaption'))}</figcaption></figure><div><div class="cut-heading"><div><h2 id="catalog-category">${esc(t('pork'))}</h2><p id="category-intro">${esc(t('categoryPorkIntro'))}</p></div>${tr('categoryCount','span')}</div><div class="cut-list" id="cut-list">${cutRows('pork')}</div></div></div></section><aside class="container cut-help"><div>${tr('cutsHelpTitle','h2')}${tr('cutsHelpText','p')}</div>${localLink('./dishes.html','goDishes','button primary')}</aside>`+deliveryRibbon;}
function cutRows(category){return cuts.filter(c=>category==='other'?!['pork','beef','offal'].includes(c.group||c.category):(c.group||c.category)===category).map(c=>`<article class="cut-row"><div><h3>${esc(c.name.ka)}</h3><p>${esc(c.use.ka)}</p></div><div class="cut-buy"><span class="cut-price${c.price>0?'':' price-pending'}">${c.price>0?c.price+' ₾ / '+esc(t(c.unit==='piece'?'perPiece':'perKg')):esc(t('priceAsk'))}</span><button type="button" class="cut-select" data-order="${c.category}" data-cut="${c.id}" aria-label="${esc(t('cutCta')+': '+c.name.ka)}">${tr('cutCta')}${arrow}</button></div></article>`).join('');}
function dishPage(){return heading('dishesHeading','dishesIntro')+`<section class="container dishes-browser"><div class="dish-filters"><div class="search-field"><label for="dish-search" data-i18n="searchDish">${esc(t('searchDish'))}</label><div><input type="search" id="dish-search" data-placeholder="searchPlaceholder" placeholder="${esc(t('searchPlaceholder'))}" maxlength="100" autocomplete="off"><button type="button" id="clear-search" data-aria="clearSearch" aria-label="${esc(t('clearSearch'))}" hidden>×</button></div></div><div class="method-field"><label for="dish-method" data-i18n="methodLabel">${esc(t('methodLabel'))}</label><select id="dish-method"><option value="" data-i18n="methodAll">${esc(t('methodAll'))}</option>${['pan','stew','boil','grill','roast','cold'].map(m=>`<option value="${m}" data-i18n="${m}">${esc(t(m))}</option>`).join('')}</select></div></div><div class="filter-bar"><div class="filter-chips" role="group" data-aria="meatType" aria-label="${esc(t('meatType'))}">${['all','pork','beef','offal'].map((cat,i)=>`<button type="button" data-meat-filter="${cat}" aria-pressed="${i===0}">${tr(cat)}</button>`).join('')}</div><p id="dish-count" role="status">${esc(t('dishCount').replace('{n}',15))}</p></div><div class="dish-grid" id="all-dishes">${dishes.map(dishCard).join('')}</div><div id="dish-empty" hidden>${tr('dishNoResults','h2')}${tr('dishNoResultsText','p')}<button type="button" class="text-button" id="reset-filters">${tr('resetFilters')}${arrow}</button><button type="button" class="button primary" data-order="any">${tr('needHelp')}</button></div></section>`+deliveryRibbon;}
const pages={home:['index.html',home,'title','description'],catalog:['catalog.html',catalog,'catalogPageTitle','catalogPageDescription'],dishes:['dishes.html',dishPage,'dishesPageTitle','dishesPageDescription']};
for(const [page,[file,render,title,description]] of Object.entries(pages)){
 let html=`<!doctype html>\n<html lang="ka"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#711b25"><meta name="robots" content="index,follow"><title>${esc(t(title))}</title><meta name="description" content="${esc(t(description))}"><link rel="icon" href="./favicon.svg" type="image/svg+xml"><link rel="preload" href="./assets/georgian-bold.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="./style.css"><link rel="stylesheet" href="./refinements.css"><link rel="stylesheet" href="./shop.css"><script src="./config.js" defer></script><script src="./content.js" defer></script><script src="./app.js" defer></script></head><body data-page="${page}">${header(page)}<main id="main">${render()}</main>${footer()}${read('order-dialogs')}${dishDialog()}<noscript><p class="no-script">MeatCO · WhatsApp: <a href="https://wa.me/995568258118">+995 568 258 118</a>. ქართული / Русский / English.</p></noscript></body></html>`;
 const publicUrl='https://axperik777.github.io/meatco-tbilisi/'+(file==='index.html'?'':file);
 html=html.replace('</head>',`<link rel="canonical" href="${publicUrl}"><meta property="og:type" content="website"><meta property="og:site_name" content="MeatCO"><meta property="og:title" content="${esc(t(title))}"><meta property="og:description" content="${esc(t(description))}"><meta property="og:url" content="${publicUrl}"><meta property="og:image" content="https://axperik777.github.io/meatco-tbilisi/assets/meatco-beef-v01.jpg"><meta name="twitter:card" content="summary_large_image"></head>`);
 if(page==='catalog')html=html.replace('</section><aside class="container cut-help">',`<details class="other-assortment">${tr('otherProducts','summary')}${tr('otherProductsText','p')}<div id="other-cuts">${cutRows('other')}</div></details></section><aside class="container cut-help">`);
 html=html.replace('<label><input type="radio" name="meat" value="any" checked>', ['poultry','lamb','veal'].map(c=>`<label data-secondary-type="${c}" hidden><input type="radio" name="meat" value="${c}">${tr(c)}</label>`).join('')+'<label><input type="radio" name="meat" value="any" checked>');
 html=html.replace(/(<([a-z0-9]+)\b[^>]*data-i18n="([^"]+)"[^>]*>)([^<]*)(<\/\2>)/g,(m,start,tag,key,old,end)=>start+esc(t(key))+end);
 fs.writeFileSync('dist/'+file,html+'\n');
}
fs.writeFileSync('dist/app.js',"'use strict';\n(()=>{\nconst strings = "+JSON.stringify(dict,null,2)+";\n"+fs.readFileSync('src/app-core.js','utf8')+"\n})();\n");
console.log('Built 3 pages with shared content and 3 locales.');
