import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const sandbox={window:{}};
vm.runInNewContext(fs.readFileSync('dist/content.js','utf8'),sandbox);
vm.runInNewContext(fs.readFileSync('src/product-search.js','utf8'),sandbox);
const {cuts,dishes}=sandbox.window.MEATCO_CONTENT;
const find=sandbox.createProductSearch(cuts,dishes,JSON.parse(fs.readFileSync('src/locales.json','utf8')));
const ids=query=>Array.from(find(query),c=>c.id);
assert.deepEqual(ids('ребра'),ids('РЁБРА'));
assert.deepEqual(ids('  говядина   печень '),['offal-beef-liver']);
assert.deepEqual(ids('печень говядина'),ids('говядина печень'));
assert.deepEqual(ids('курица'),['chicken']);
assert.deepEqual(ids('ქათამი'),['chicken']);
assert.deepEqual(ids('индюшка'),['turkey']);
assert.ok(ids('холодец').includes('offal-pork-feet'));
assert.ok(ids('ხინკალი').includes('mixed-mince'));
assert.ok(ids('khinkali').includes('mixed-mince'));
assert.deepEqual(ids('zzz несуществующий товар'),[]);
assert.equal(ids('').length,46);
assert.ok(ids('говядна').includes('beef-tenderloin'));
assert.deepEqual(ids('ребар'),['pork-ribs']);
assert.deepEqual(ids('chiken'),['chicken']);
assert.deepEqual(ids('turky'),['turkey']);
assert.ok(ids('ღვიძილი').includes('offal-beef-liver'));
assert.ok(find('говядна').fuzzy);
assert.ok(!find('говядина').fuzzy);
assert.deepEqual(ids('молоко'),[]);
console.log('Product search: 19 multilingual and typo scenarios passed.');
