"""Build the committed WOFF2 assets; requires fonttools[woff] and brotli.
Run from repo root. Original project fonts are kept outside the public dist.
"""
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools import subset
from fontTools.varLib.instancer import instantiateVariableFont
import base64, collections, hashlib, json, gzip

root=Path(__file__).resolve().parents[1]
source=root/'tools/font-sources'
out=root/'dist/assets/fonts'
out.mkdir(parents=True,exist_ok=True)
latin=set(range(0x20,0x100))|set(range(0x410,0x450))|{0x401,0x451,0x490,0x491,0x20BE,0x2116,0x2122,0x2190,0x2191,0x2192,0x2193,0x2197,0x2212}|set(range(0x2000,0x2070))
geo=set(range(0x20,0x7F))|set(range(0x10D0,0x10F1))|set(range(0x1C90,0x1CB1))|{0x00A0,0x00A9,0x00B7,0x00D7,0x20BE,0x2116,0x2190,0x2191,0x2192,0x2193,0x2197,0x2212}|set(range(0x2010,0x2027))
locales=json.loads((root/'src/locales.json').read_text(encoding='utf-8'))
latin_range='U+0020-024F,U+0400-052F,U+2000-206F,U+20BE,U+2116,U+2122,U+2190-2193,U+2197,U+2212'
geo_range='U+0020-00FF,U+10A0-10FF,U+1C90-1CBF,U+2D00-2D2F,U+2000-206F,U+20BE,U+2116,U+2190-2193,U+2197,U+2212'
fonts={}
inventory=[]
def build(name,file,chars,weight=None):
    font=TTFont(source/file)
    if weight is not None: font=instantiateVariableFont(font,{'wght':weight},inplace=False)
    options=subset.Options()
    options.flavor='woff2';options.layout_features=['*'];options.hinting=False
    options.notdef_glyph=True;options.notdef_outline=True
    options.name_IDs=[0,1,2,3,4,5,6,13,14];options.name_legacy=True
    sub=subset.Subsetter(options=options);sub.populate(unicodes=chars);sub.subset(font)
    font.flavor='woff2';font.recalcTimestamp=False;font.save(out/(name+'.woff2'))
    fonts[name]=font
    inventory.append({'file':name+'.woff2','weight':font['OS/2'].usWeightClass,'bytes':(out/(name+'.woff2')).stat().st_size,'glyphs':len(font.getBestCmap()),'characters':''.join(chr(c) for c in sorted(font.getBestCmap())),'sha256':hashlib.sha256((out/(name+'.woff2')).read_bytes()).hexdigest()})
build('manrope-400','manrope-regular.ttf',latin)
build('manrope-600','Manrope-variable.ttf',latin,600)
build('manrope-700','Manrope-variable.ttf',latin,700)
build('georgian-400','georgian-regular.ttf',geo)
build('georgian-700','georgian-bold.ttf',geo)
build('prata-400','prata.ttf',set(map(ord,locales['ru']['appHero']+locales['en']['appHero'])))

def metrics(font,scale=1):
    upm=font['head'].unitsPerEm
    return f'size-adjust:{scale*100:.4f}%;ascent-override:{font["hhea"].ascent/upm/scale*100:.4f}%;descent-override:{-font["hhea"].descent/upm/scale*100:.4f}%;line-gap-override:0%;'
def face(family,src,weight,display,metric,unicode=''):
    return '@font-face{font-family:"'+family+'";src:'+src+';font-style:normal;font-weight:'+str(weight)+';font-display:'+display+';'+metric+('unicode-range:'+unicode+';' if unicode else '')+'}\n'

css='/* Generated by tools/build-fonts.py. Georgian WOFF2 is inline: no extra font request or Arial flash. */\n'
for w in [400,600,700]:
    f=fonts['manrope-'+str(w)]
    css+=face('Manrope',f'url("./assets/fonts/manrope-{w}.woff2") format("woff2")',w,'swap',metrics(f),latin_range)
for weight,file in [(400,'georgian-400'),(700,'georgian-700')]:
    payload=base64.b64encode((out/(file+'.woff2')).read_bytes()).decode()
    css+=face('NotoGeo',f'url("data:font/woff2;base64,{payload}") format("woff2")',weight,'swap',metrics(fonts[file]),geo_range)
css+=face('Prata','url("./assets/fonts/prata-400.woff2") format("woff2")',400,'optional',metrics(fonts['prata-400']),latin_range)

# Match fallback advance widths using the real RU/EN strings; keep target vertical metrics.
locales=json.loads((root/'src/locales.json').read_text(encoding='utf-8'))
corpus=' '.join(locales['ru'].values())+' '+' '.join(locales['en'].values())
def width(font,text):
    cmap=font.getBestCmap();hm=font['hmtx'].metrics;upm=font['head'].unitsPerEm
    return sum(hm[cmap[ord(c)]][0]/upm for c in text if ord(c) in cmap)
def fallback(family,localname,filename,target,weight,text):
    fallback_font=TTFont(Path('C:/Windows/Fonts')/filename)
    supported=set(target.getBestCmap())&set(fallback_font.getBestCmap())
    common=''.join(c for c in text if ord(c) in supported)
    ratio=width(target,common)/width(fallback_font,common)
    return face(family,f'local("{localname}")',weight,'swap',metrics(target,ratio))
for w in [400,600,700]:
    target=fonts['manrope-'+str(w)]
    css+=fallback('Manrope Segoe','Segoe UI' if w==400 else 'Segoe UI Bold','segoeui.ttf' if w==400 else 'segoeuib.ttf',target,w,corpus)
    css+=fallback('Manrope Arial','Arial' if w==400 else 'Arial Bold','arial.ttf' if w==400 else 'arialbd.ttf',target,w,corpus)
    # Roboto's regular x-height is approximately .5283em. It is local-only.
    ratio=.54/.5283
    css+=face('Manrope Roboto','local("Roboto")' if w==400 else 'local("Roboto Bold")',w,'swap',metrics(target,ratio))
headline=locales['ru']['appHero']+' '+locales['en']['appHero']
css+=fallback('Prata Georgia','Georgia','georgia.ttf',fonts['prata-400'],400,headline)
css+=fallback('Prata Times','Times New Roman','times.ttf',fonts['prata-400'],400,headline)
for w in [400,600,700]:
    target=fonts['georgian-400' if w==400 else 'georgian-700']
    css+=face('NotoGeo System','local("Noto Sans Georgian")' if w==400 else 'local("Noto Sans Georgian Bold")',w,'swap',metrics(target),geo_range)
(root/'dist/fonts.css').write_text(css,encoding='utf-8')
stats={'files':inventory,'cssBytes':len(css.encode()),'cssGzipBytes':len(gzip.compress(css.encode(),mtime=0))}
stats['latinHomeFontBytesIncludingCriticalCss']=stats['cssGzipBytes']+sum(x['bytes'] for x in inventory if x['file'].startswith(('manrope','prata')))
stats['georgianHomeFontBytesIncludingCriticalCss']=stats['cssGzipBytes']
(root/'docs/font-build.json').write_text(json.dumps(stats,indent=2),encoding='utf-8')
print(json.dumps(stats,indent=2))
