import {productPhoto,categoryPhoto,homeImagePreload} from './image-assets.mjs';
export function storefront({tr,t,esc,wa,arrow,cuts,faq}){
 const featured=['pork-flesh','beef-round','pork-ribs','beef-tenderloin','mixed-mince','offal-beef-liver'];
 const ordered=[...featured.map(id=>cuts.find(c=>c.id===id)),...cuts.filter(c=>!featured.includes(c.id))];
 const svg=body=>`<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
 const icons={
  pin:svg('<path d="M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>'),
  calendar:svg('<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18m-13 5h3"/>'),
  home:svg('<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-8H9v8H4a1 1 0 0 1-1-1Z"/>'),
  search:svg('<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>'),
  catalog:svg('<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>'),
  weight:svg('<path d="M5 8h14l2 12H3L5 8Z"/><circle cx="12" cy="5" r="3"/>'),
  check:svg('<path d="m5 12 4 4L19 6"/>'),
  cart:svg('<path d="M3 8h18l-2 12H5L3 8Zm4 0 3-5m7 5-3-5M9 12v4m6-4v4"/>'),
  chat:svg('<path d="M20 11.5a8.5 8.5 0 0 1-8.5 8.5H3l2-4.5A8.5 8.5 0 1 1 20 11.5Z"/><path d="M8 10h7m-7 4h4"/>')
 };
 const logo=()=>`<img class="brand-logo" src="./assets/brand/meatco-logo-small.webp" width="360" height="128" loading="eager" decoding="async" alt="MEAT CO — Butcher's Pride">`;
 const photo=c=>c.image&&c.photoStatus!=='pending'&&cuts.filter(other=>other.image===c.image).length===1?c.image:'./assets/products/photo-pending.svg';
 function card(c,index=0,view='catalog',active=false){const image=photo(c);return `<article class="meat-card" data-product-card="${c.id}" ${index>=6?'hidden':''}><div class="product-visual"><button type="button" class="meat-photo" data-view-product="${c.id}" aria-label="${esc(c.name.ka)}">${productPhoto(image,esc(c.name.ka),{view,eager:active&&index<(view==='catalog'?4:2),high:active&&index<2})}${tr('photoSoon','span',`class="photo-pending-label" ${image.endsWith('.svg')?'':'hidden'}`)}</button></div><div class="meat-copy"><p class="meat-price${c.price>0?'':' price-pending'}">${c.price>0?c.price+' ₾ <span>/ '+esc(t(c.unit==='piece'?'perPiece':'perKg'))+'</span>':esc(t('priceAsk'))}</p><h3><button type="button" data-view-product="${c.id}">${esc(c.name.ka)}</button></h3><p class="meat-category">${esc(t(c.category))}</p><div class="meat-buy"><button class="meat-select" type="button" data-add-cut="${c.id}" aria-label="${esc(t('addToCart')+': '+c.name.ka)}"><span aria-hidden="true">+</span>${tr('addShort')}</button><div class="card-quantity" data-card-quantity="${c.id}" hidden><button type="button" data-cart-step="-1" data-cart-id="${c.id}" aria-label="${esc(t('decrease')+': '+c.name.ka)}">−</button><button type="button" class="card-quantity-value" data-cart-open></button><button type="button" data-cart-step="1" data-cart-id="${c.id}" aria-label="${esc(t('increase')+': '+c.name.ka)}">+</button></div></div></div></article>`;}
 const catImages={pork:'pork-ribs',beef:'beef-tenderloin',offal:'offal-beef-liver',other:'chicken'};
 const categoryKey=cat=>cat==='other'?'categoryMore':cat;
 function catalogSection(initial){return `<section class="container catalog-browser" id="catalog"><div class="catalog-layout"><div class="catalog-tools" id="catalog-tools"><div class="catalog-search">${icons.search}<label class="sr-only" for="product-search" data-i18n="productSearch">${esc(t('productSearch'))}</label><input type="search" id="product-search" autocomplete="off" maxlength="100" data-placeholder="quickFindPlaceholder" placeholder="${esc(t('quickFindPlaceholder'))}" enterkeyhint="search"><button type="button" id="clear-product-search" data-aria="clearProductSearch" aria-label="${esc(t('clearProductSearch'))}" hidden>×</button></div><nav class="catalog-tabs" data-aria="navCatalog" aria-label="${esc(t('navCatalog'))}">${['all','beef','pork','offal','other'].map((cat,i)=>`<button type="button" data-category="${cat}" aria-pressed="${i===0}">${tr(categoryKey(cat))}</button>`).join('')}</nav></div><div class="catalog-content"><div class="catalog-heading"><h1 id="catalog-title" data-i18n="appCatalog">${esc(t('appCatalog'))}</h1></div><div class="catalog-status"><p id="product-count" role="status" hidden></p>${tr('catalogPriceHint','span')}</div><div class="meat-grid" id="product-grid">${ordered.map((c,i)=>card(c,i,'catalog',initial==='catalog')).join('')}</div><div class="catalog-more"><button type="button" id="more-products" class="button secondary">${tr('showMore')}<span aria-hidden="true">↓</span></button></div><div id="product-empty" class="product-empty" hidden>${icons.search}<h3 id="catalog-empty-title">${esc(t('productNoResults'))}</h3><p id="catalog-empty-description">${esc(t('productNoResultsText'))}</p><button type="button" id="search-all-categories" class="text-button" hidden>${tr('searchBeyondCategory')}${arrow}</button><button type="button" class="text-button" id="reset-products">${tr('resetFilters')}${arrow}</button></div></div></div></section>`;}
 function delivery(){return `<section id="delivery" class="container service-section"><div class="service-heading">${tr('serviceTitle','h2')}</div><div class="service-steps">${[1,2,3].map(n=>`<article><span class="step-number">${n}</span><div>${tr('control'+n+'Title','h3')}${tr('control'+n+'Text','p')}</div></article>`).join('')}</div></section>`;}
 function b2b(){return `<section class="b2b-brand container" id="restaurants"><div class="b2b-brand-title">${tr('navB2b','span')}</div><div class="b2b-brand-copy">${tr('b2bTitle','h2')}${tr('b2bText','p')}<a class="text-button" data-wholesale ${wa}>${tr('b2bCta')}${arrow}</a></div></section>`;}
 function eventCard(){return `<aside class="event-card container"><div>${icons.calendar}${tr('eventEyebrow','span')}</div>${tr('eventTitle','h2')}${tr('eventCopy','p')}<a class="text-button" data-event-whatsapp ${wa}>${tr('eventCta')}${arrow}</a></aside>`;}
 function appFeed(initial){return `<section class="app-feed container"><div class="feed-greeting">${tr('appHero','h1')}${tr('appHeroCopy','p','class="feed-subtitle"')}</div><ul class="trust-chips" aria-label="${esc(t('trustLabel'))}" data-aria="trustLabel">${[['pin','trustCity'],['weight','trustWeight'],['check','trustNoAccount']].map(([icon,key])=>`<li>${icons[icon]}${tr(key)}</li>`).join('')}</ul><div class="quick-categories" role="group" data-aria="homeCategories" aria-label="${esc(t('homeCategories'))}">${['beef','pork','offal','other'].map(cat=>`<button type="button" data-app-category="${cat}">${categoryPhoto(photo(cuts.find(c=>c.id===catImages[cat])))}${tr(categoryKey(cat))}</button>`).join('')}</div><div class="feed-heading">${tr('homeSelection','h2')}<button type="button" data-app-tab="catalog">${tr('allProducts')}<span aria-hidden="true">→</span></button></div><div class="home-product-rail">${featured.map((id,i)=>card(cuts.find(c=>c.id===id),i,'home',initial==='home')).join('')}</div>${tr('brandSmall','p','class="feed-brand-line"')}</section>`;}
 function helpPanel(){return `<section class="help-screen container">${tr('helpTitle','h1')}${tr('helpIntro','p')}<div class="help-actions"><a data-whatsapp ${wa}>${icons.chat}${tr('helpContact')}${arrow}</a><a href="tel:+995568258118">${tr('callUs')}<span>+995 568 258 118</span></a></div><a class="contact-address" href="https://www.google.com/maps/search/?api=1&amp;query=3%20Mevele%20Street%2C%20Tbilisi" target="_blank" rel="noopener noreferrer">${icons.pin}<span>${tr('contactAddressLabel','small')}${tr('contactAddress','strong')}</span>${arrow}</a></section>`+delivery()+eventCard()+b2b()+faq()+`<div class="container help-privacy"><button type="button" class="text-button" data-open-privacy>${tr('privacyOpen')}</button><span>© MeatCO</span></div>`;}
 function appPage(initial='home'){return `<div class="app-frame" data-initial-screen="${initial}"><div data-app-panel="home" ${initial!=='home'?'hidden':''}>${appFeed(initial)}</div><div data-app-panel="catalog" ${initial!=='catalog'?'hidden':''}>${catalogSection(initial)}</div><div data-app-panel="help" hidden>${helpPanel()}</div></div>`;}
 function appHeader(){return `<a class="skip" href="#main">${tr('skip')}</a><header class="header"><div class="container header-inner"><a class="brand-lockup" data-local href="./index.html" aria-label="MeatCO">${logo()}</a><div class="header-actions"><div class="languages" role="group" data-aria="languageLabel" aria-label="${esc(t('languageLabel'))}"><button type="button" data-lang="ka" aria-label="ქართული" aria-pressed="true">ქარ</button><button type="button" data-lang="ru" aria-label="Русский" aria-pressed="false">RU</button><button type="button" data-lang="en" aria-label="English" aria-pressed="false">EN</button></div><a class="app-whatsapp" data-whatsapp ${wa} aria-label="WhatsApp">${icons.chat}</a></div></div><button id="menu-toggle" type="button" class="menu-toggle" hidden aria-controls="mobile-nav" aria-expanded="false"></button><nav id="mobile-nav" hidden></nav></header>`;}
 function appFooter(){return `<div hidden><span id="year">2026</span><button id="privacy-open" type="button">Privacy</button></div><nav class="mobile-bar app-tabbar" data-aria="navLabel" aria-label="${esc(t('navLabel'))}"><button type="button" data-app-tab="home">${icons.home}${tr('appHome')}</button><button type="button" data-app-tab="catalog">${icons.catalog}${tr('navCatalog')}</button><button type="button" class="bottom-cart" data-cart-open><span class="nav-cart-icon">${icons.cart}<span data-cart-count hidden>0</span></span><span data-cart-total hidden></span><span class="empty-cart-label" data-i18n="cartNav">${esc(t('cartNav'))}</span></button><button type="button" data-app-tab="help">${icons.chat}${tr('appHelp')}</button></nav>`;}
 return {imagePreload:()=>homeImagePreload(photo(cuts.find(c=>c.id===featured[0]))),header:appHeader,footer:appFooter,home:()=>appPage('home'),catalog:()=>appPage('catalog')};
}
