export function storefront({tr,t,esc,localLink,wa,arrow,cuts,faq}){
 const featured=['beef-tenderloin','pork-flesh','pork-ribs','beef-round','pork-tenderloin','beef-brisket','mixed-mince','offal-beef-liver'];
 const ordered=[...featured.map(id=>cuts.find(c=>c.id===id)),...cuts.filter(c=>!featured.includes(c.id))];
 const svg=body=>`<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
 const icons={
  pin:svg('<path d="M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>'),
  calendar:svg('<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18m-13 5h3m3 0h2"/>'),
  home:svg('<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-8H9v8H4a1 1 0 0 1-1-1Z"/>'),
  search:svg('<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>'),
  catalog:svg('<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>'),
  heart:svg('<path d="M20.7 4.8a5.5 5.5 0 0 0-7.8 0L12 5.9l-.9-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.7-8.4a5.5 5.5 0 0 0 0-7.8Z"/>'),
  cart:svg('<path d="M3 8h18l-2 12H5L3 8Zm4 0 3-5m7 5-3-5M9 12v4m6-4v4"/>'),
  video:svg('<rect x="3" y="5" width="13" height="14" rx="3"/><path d="m16 10 5-3v10l-5-3"/>'),
  chat:svg('<path d="M20 11.5a8.5 8.5 0 0 1-8.5 8.5H3l2-4.5A8.5 8.5 0 1 1 20 11.5Z"/><path d="M8 10h7m-7 4h4"/>')
 };
 const logo=(cls='brand-logo')=>`<img class="${cls}" src="./assets/brand/meatco-logo.png" width="540" height="192" alt="MEAT CO — Butcher's Pride">`;
 const emblem=()=>'<img src="./assets/brand/meatco-mark.png" width="40" height="40" alt="" aria-hidden="true">';
 function card(c,index=0){return `<article class="meat-card" data-product-card="${c.id}" ${index>=12?'hidden':''}><div class="product-visual"><button type="button" class="meat-photo" data-view-product="${c.id}" aria-label="${esc(c.name.ka)}"><img src="${c.image}" srcset="${c.image.replace('.webp','-small.webp')} 480w, ${c.image} 960w" sizes="(max-width:600px) 50vw, (max-width:1000px) 30vw, 25vw" width="960" height="960" loading="${index<4?'eager':'lazy'}" alt="${esc(c.name.ka)}"><span class="card-brand">${emblem()}</span></button><button type="button" class="favorite-toggle" data-favorite="${c.id}" aria-pressed="false" aria-label="${esc(t('saveFavorite')+': '+c.name.ka)}">${icons.heart}</button></div><div class="meat-copy"><p class="meat-price${c.price>0?'':' price-pending'}">${c.price>0?c.price+' ₾ <span>/ '+esc(t(c.unit==='piece'?'perPiece':'perKg'))+'</span>':esc(t('priceAsk'))}</p><h3><button type="button" data-view-product="${c.id}">${esc(c.name.ka)}</button></h3><p class="meat-category">${esc(t(c.category))}</p><p class="meat-use">${esc(c.use.ka)}</p><div class="meat-buy"><button class="meat-select" type="button" data-add-cut="${c.id}" aria-label="${esc(t('addToCart')+': '+c.name.ka)}"><span aria-hidden="true">+</span>${tr('addShort')}</button><div class="card-quantity" data-card-quantity="${c.id}" hidden><button type="button" data-cart-step="-1" data-cart-id="${c.id}" aria-label="${esc(t('decrease')+': '+c.name.ka)}">−</button><button type="button" class="card-quantity-value" data-cart-open></button><button type="button" data-cart-step="1" data-cart-id="${c.id}" aria-label="${esc(t('increase')+': '+c.name.ka)}">+</button></div></div></div></article>`;}
 const catImages={all:'mixed-mince',pork:'pork-ribs',beef:'beef-tenderloin',offal:'offal-beef-liver',other:'chicken'};
 function catalogSection(){return `<section class="container catalog-browser" id="catalog"><div class="catalog-layout"><div class="catalog-tools" id="catalog-tools"><div class="catalog-search">${icons.search}<label class="sr-only" for="product-search" data-i18n="productSearch">${esc(t('productSearch'))}</label><input type="search" id="product-search" autocomplete="off" maxlength="100" data-placeholder="quickFindPlaceholder" placeholder="${esc(t('quickFindPlaceholder'))}" enterkeyhint="search"><button type="button" id="clear-product-search" data-aria="clearProductSearch" aria-label="${esc(t('clearProductSearch'))}" hidden>×</button><button type="button" class="filter-open" data-filter-open aria-label="ფილტრები" data-aria="filterLabel"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 6h16M7 12h10M10 18h4"/></svg></button></div><nav class="catalog-tabs" data-aria="navCatalog" aria-label="${esc(t('navCatalog'))}">${['all','pork','beef','offal','other','favorites'].map((cat,i)=>`<button type="button" data-category="${cat}" aria-pressed="${i===0}">${cat==='favorites'?icons.heart:`<img src="${cuts.find(c=>c.id===catImages[cat]).image.replace('.webp','-small.webp')}" width="44" height="44" alt="">`}${tr(cat)}</button>`).join('')}</nav></div><div class="catalog-content"><div class="catalog-heading"><h1 id="catalog-title" data-i18n="appCatalog">${esc(t('appCatalog'))}</h1><label class="catalog-sort"><span class="sr-only" data-i18n="sortLabel">${esc(t('sortLabel'))}</span><select id="product-sort"><option value="default" data-i18n="sortDefault">${esc(t('sortDefault'))}</option><option value="name" data-i18n="sortName">${esc(t('sortName'))}</option><option value="price" data-i18n="sortPrice">${esc(t('sortPrice'))}</option></select></label></div><div class="catalog-status"><p id="product-count" role="status">${esc(t('productCount').replace('{n}',cuts.length))}</p>${tr('catalogPriceHint','span')}</div><div class="meat-grid" id="product-grid">${ordered.map(card).join('')}</div><div class="catalog-more"><button type="button" id="more-products" class="button secondary">${tr('showMore')}<span aria-hidden="true">↓</span></button></div><div id="product-empty" class="product-empty" hidden>${icons.search}<h3 id="catalog-empty-title">${esc(t('productNoResults'))}</h3><p id="catalog-empty-description">${esc(t('productNoResultsText'))}</p><button type="button" id="search-all-categories" class="text-button" hidden>${tr('searchBeyondCategory')}${arrow}</button><button type="button" class="text-button" id="reset-products">${tr('resetFilters')}${arrow}</button></div>${tr('priceNote','p','class="catalog-note"')}</div></div></section>`;}
 function delivery(){return `<section id="delivery" class="container service-section"><div class="service-heading">${tr('serviceTitle','h2')}${tr('serviceIntro','p')}<a class="text-button" data-video-general ${wa}>${icons.video}${tr('videoCtaShort')}${arrow}</a></div><div class="service-steps">${[1,2,3].map(n=>`<article><span class="step-number">${n}</span><div>${tr('control'+n+'Title','h3')}${tr('control'+n+'Text','p')}</div></article>`).join('')}</div></section>`;}
 function b2b(){return `<section class="b2b-brand container" id="restaurants"><div class="b2b-brand-title">${logo()}${tr('navB2b','span')}</div><div class="b2b-brand-copy">${tr('b2bTitle','h2')}${tr('b2bText','p')}<a class="button primary" data-wholesale ${wa}>${tr('b2bCta')}${arrow}</a></div></section>`;}
 
 function eventCard(){return `<aside class="event-card"><div class="event-card-icon">${icons.calendar}</div><div>${tr('eventEyebrow','p','class="event-eyebrow"')}${tr('eventTitle','h2')}${tr('eventCopy','p')}<a class="text-button" data-event-whatsapp ${wa}>${tr('eventCta')}${arrow}</a></div></aside>`;}
 function appFeed(){return `<section class="app-feed container"><div class="feed-greeting"><div><p>MEAT CO · TBILISI</p>${tr('appHero','h1')}</div><img src="./assets/brand/meatco-mark.png" width="92" height="100" alt=""></div>${tr('appHeroCopy','p','class="feed-subtitle"')}<a class="video-trust" data-video-general ${wa}><span class="video-trust-icon">${icons.video}</span><span>${tr('videoTrustTitle','strong')}${tr('videoTrustCopy','small')}<span class="video-trust-action">${tr('videoTrustCta')}${arrow}</span></span></a><div class="feed-heading">${tr('homeCategories','h2')}</div><div class="quick-categories">${['beef','pork','offal','other'].map(cat=>`<button type="button" data-app-category="${cat}"><img src="${cuts.find(c=>c.id===catImages[cat]).image.replace('.webp','-small.webp')}" width="80" height="80" alt="">${tr(cat)}</button>`).join('')}</div><div class="feed-heading">${tr('homeSelection','h2')}<button type="button" data-app-tab="catalog">${tr('allProducts')}${arrow}</button></div><div class="home-product-rail">${featured.slice(0,6).map(id=>card(cuts.find(c=>c.id===id),0)).join('')}</div><button type="button" class="button primary feed-main-cta" data-app-tab="catalog">${tr('viewCatalog')}${arrow}</button>${eventCard()}<div class="install-hint" id="install-hint" hidden><button class="install-dismiss" type="button" data-install-dismiss data-aria="dismiss" aria-label="${esc(t('dismiss'))}">×</button>${tr('installTitle','strong')}${tr('installText','p')}<button type="button" class="text-button" data-install-open>${tr('installAction')}</button></div>${tr('brandSmall','p','class="feed-brand-line"')}</section>`;}
 function helpPanel(){return `<section class="help-screen container">${tr('helpTitle','h1')}${tr('helpIntro','p')}<div class="help-actions"><a data-whatsapp ${wa}>${icons.chat}${tr('helpContact')}${arrow}</a><a href="tel:+995568258118">${tr('callUs')}<span>+995 568 258 118</span></a><a data-event-whatsapp ${wa}>${icons.calendar}${tr('eventCta')}${arrow}</a><button type="button" data-app-business>${tr('navB2b')}${arrow}</button><a data-local href="./dishes.html">${tr('navDishes')}${arrow}</a></div><a class="contact-address" href="https://www.google.com/maps/search/?api=1&amp;query=3%20Mevele%20Street%2C%20Tbilisi" target="_blank" rel="noopener noreferrer">${icons.pin}<span>${tr('contactAddressLabel','small')}${tr('contactAddress','strong')}</span>${arrow}</a></section>`+delivery()+b2b()+faq()+`<div class="container help-privacy"><button type="button" class="text-button" data-open-privacy>${tr('privacyOpen')}</button><span>© MeatCO · Tbilisi</span></div>`;}
 function appPage(initial='home'){return `<div class="app-frame" data-initial-screen="${initial}"><div data-app-panel="home" ${initial!=='home'?'hidden':''}>${appFeed()}</div><div data-app-panel="catalog" ${initial!=='catalog'?'hidden':''}>${catalogSection()}</div><div data-app-panel="help" hidden>${helpPanel()}</div></div>`;}
 function appHeader(){return `<a class="skip" href="#main">${tr('skip')}</a><header class="header"><div class="container header-inner"><a class="brand-lockup" data-local href="./index.html" aria-label="MeatCO">${logo()}</a><div class="header-actions"><div class="languages" role="group" data-aria="languageLabel" aria-label="${esc(t('languageLabel'))}"><button type="button" data-lang="ka" aria-label="ქართული" aria-pressed="true">ქარ</button><button type="button" data-lang="ru" aria-label="Русский" aria-pressed="false">RU</button><button type="button" data-lang="en" aria-label="English" aria-pressed="false">EN</button></div><a class="app-whatsapp" data-whatsapp ${wa} aria-label="WhatsApp">${icons.chat}</a></div></div><button id="menu-toggle" type="button" class="menu-toggle" hidden aria-controls="mobile-nav" aria-expanded="false" aria-label="${esc(t('menu'))}"></button><nav id="mobile-nav" hidden></nav></header>`;}
 function appFooter(){return `<div hidden><span id="year">2026</span><button id="privacy-open" type="button">Privacy</button></div><nav class="mobile-bar app-tabbar" data-aria="navLabel" aria-label="${esc(t('navLabel'))}"><button type="button" data-app-tab="home">${icons.home}${tr('appHome')}</button><button type="button" data-app-tab="catalog">${icons.catalog}${tr('navCatalog')}</button><button type="button" class="bottom-cart" data-cart-open><span class="nav-cart-icon">${icons.cart}<span data-cart-count>0</span></span><span data-cart-total hidden></span><span class="empty-cart-label" data-i18n="cartNav">${esc(t('cartNav'))}</span></button><button type="button" data-app-tab="help">${icons.chat}${tr('appHelp')}</button></nav>`;}
 return {header:appHeader,footer:appFooter,home:()=>appPage('home'),catalog:()=>appPage('catalog')};

}
