export function storefront({tr,t,esc,localLink,wa,arrow,cuts,faq}) {
 const featured=['beef-tenderloin','pork-flesh','pork-ribs','beef-round','pork-tenderloin','beef-brisket','mixed-mince','offal-beef-liver'];
 const ordered=[...featured.map(id=>cuts.find(c=>c.id===id)),...cuts.filter(c=>!featured.includes(c.id))];
 const mark='<span class="brand-seal" aria-hidden="true">M<span>CO</span></span>';
 const brand='<span class="wordmark">MeatCO</span>';
 const navItems=[['./index.html','navHome','home'],['./catalog.html','navCatalog','catalog'],['./index.html#delivery','navDelivery','delivery'],['./index.html#restaurants','navB2b','b2b']];
 const nav=page=>navItems.map(([href,key,id])=>`<a data-local href="${href}" ${id===page?'aria-current="page"':''}>${tr(key)}</a>`).join('');
 function header(page){return `<a class="skip" href="#main">${tr('skip')}</a><div class="utility-strip"><div class="container"><span>MeatCO · ${tr('utilityDelivery')}</span><a href="tel:+995568258118">+995 568 258 118</a></div></div><header class="header"><div class="container header-inner"><a class="brand-lockup" data-local href="./index.html" aria-label="MeatCO">${brand}<span class="brand-location">TBILISI</span></a><nav class="desktop-nav" data-aria="navLabel" aria-label="${esc(t('navLabel'))}">${nav(page)}</nav><div class="header-actions"><div class="languages" role="group" data-aria="languageLabel" aria-label="${esc(t('languageLabel'))}"><button type="button" data-lang="ka" aria-label="ქართული" aria-pressed="true">ქარ</button><button type="button" data-lang="ru" aria-label="Русский" aria-pressed="false">RU</button><button type="button" data-lang="en" aria-label="English" aria-pressed="false">EN</button></div><a class="header-wa" data-whatsapp ${wa}>WhatsApp ${arrow}</a><button type="button" class="menu-toggle" id="menu-toggle" aria-expanded="false" aria-controls="mobile-nav" data-aria="menu" aria-label="${esc(t('menu'))}"><span></span><span></span></button></div></div><nav id="mobile-nav" class="mobile-nav container" hidden data-aria="navLabel" aria-label="${esc(t('navLabel'))}">${nav(page)}</nav></header>`;}
 function footer(){return `<footer class="brand-footer"><div class="container footer-shop"><div class="footer-brand">${mark}${tr('footerTag','p')}</div><div>${tr('footerCatalog','strong')}${localLink('./catalog.html?category=pork','pork')}${localLink('./catalog.html?category=beef','beef')}${localLink('./catalog.html?category=offal','offal')}${localLink('./dishes.html','navDishes')}</div><div>${tr('footerOrder','strong')}${localLink('./index.html#delivery','deliveryTerms')}${localLink('./index.html#restaurants','navB2b')}<a href="tel:+995568258118">+995 568 258 118</a><a data-whatsapp ${wa}>WhatsApp ↗</a></div></div><div class="container footer-wordmark" aria-hidden="true">MeatCO<span>TBILISI</span></div><div class="container footer-bottom"><span>© <span id="year">2026</span> MeatCO</span>${tr('photoNote')}<button type="button" id="privacy-open" data-i18n="privacy">${esc(t('privacy'))}</button></div></footer><div class="mobile-bar"><span class="wordmark">MeatCO</span><a class="button primary" data-whatsapp ${wa}>WhatsApp ${arrow}</a></div>`;}
 function card(c,index=0,hide=false){return `<article class="meat-card" data-product-card="${c.id}" ${hide?'hidden':''}><button type="button" class="meat-photo" data-order="${c.category}" data-cut="${c.id}" aria-label="${esc(t('cutCta')+': '+c.name.ka)}"><img src="${c.image}" srcset="${c.image.replace('.webp','-small.webp')} 480w, ${c.image} 960w" sizes="(max-width:600px) 50vw, (max-width:1000px) 33vw, 25vw" width="960" height="960" loading="lazy" alt="${esc(c.name.ka)}"><span class="card-brand" aria-hidden="true">MeatCO</span></button><div class="meat-copy"><p class="meat-category">${esc(t(c.category))}</p><h3>${esc(c.name.ka)}</h3><p class="meat-use">${esc(c.use.ka)}</p><div class="meat-buy"><p class="meat-price${c.price>0?'':' price-pending'}">${c.price>0?c.price+' ₾ <span>/ '+esc(t(c.unit==='piece'?'perPiece':'perKg'))+'</span>':esc(t('priceAsk'))}</p><button class="meat-select" type="button" data-order="${c.category}" data-cut="${c.id}" aria-label="${esc(t('cutCta')+': '+c.name.ka)}">${tr('cutCta')}${arrow}</button></div></div></article>`;}
 function categoryNav(){return `<nav class="category-rail container" data-aria="navCatalog" aria-label="${esc(t('navCatalog'))}">${['pork','beef','offal','other'].map(cat=>`<a data-local href="./catalog.html?category=${cat}">${tr(cat)}<span>${cuts.filter(c=>cat==='other'?!['pork','beef','offal'].includes(c.group||c.category):(c.group||c.category)===cat).length}</span>${arrow}</a>`).join('')}</nav>`;}
 function delivery(){return `<section id="delivery" class="container service-section"><div class="service-heading">${mark}${tr('serviceEyebrow','p','class="eyebrow"')}${tr('serviceTitle','h2')}${tr('serviceIntro','p')}<button class="button primary" type="button" data-order="any">${tr('serviceCta')}${arrow}</button></div><div class="service-steps">${[1,2,3].map(n=>`<article><span class="step-number">0${n}</span><div>${tr('control'+n+'Title','h3')}${tr('control'+n+'Text','p')}</div></article>`).join('')}<div class="delivery-zone">${tr('navDelivery','strong')}<p>${tr('vake')} · ${tr('saburtalo')} · ${tr('didi')}</p>${tr('nearbyShort','span')}</div></div></section>`;}
 function extras(){return `<section class="container grocery-section"><div><p class="eyebrow">MeatCO ${tr('extrasEyebrow')}</p>${tr('groceryTitle','h2')}${tr('groceryIntro','p')}</div><div class="grocery-options">${[['vegetables','extraVegetables'],['fruit','extraFruit'],['eggs','extraEggs']].map(([id,key])=>`<button type="button" data-extra-choice="${id}" aria-pressed="false">${tr(key)}<span class="extra-checkmark" aria-hidden="true">+</span></button>`).join('')}<p id="extras-summary" role="status">${esc(t('extrasNone'))}</p></div></section>`;}
 function b2b(){return `<section class="b2b-brand container" id="restaurants"><div class="b2b-brand-title"><span class="wordmark">MeatCO</span><span>BUSINESS</span></div><div class="b2b-brand-copy">${tr('b2bEyebrow','p','class="eyebrow"')}${tr('b2bTitle','h2')}${tr('b2bText','p')}<div class="b2b-details">${[1,2,3].map(n=>`<span>${tr('b2b'+n+'Title')}</span>`).join('')}</div><a class="button light-button" data-wholesale ${wa}>${tr('b2bCta')}${arrow}</a></div></section>`;}
 function home(){const heroCut=cuts.find(c=>c.id==='beef-tenderloin');return `<section class="store-hero container"><div class="store-hero-copy"><p class="eyebrow">MeatCO · TBILISI</p>${tr('heroHeading','h1')}${tr('heroCopy','p','class="store-hero-description"')}<div class="hero-buttons">${localLink('./catalog.html','viewCatalog','button light-button')}<a data-whatsapp ${wa} class="hero-catalog-link">${tr('heroWhatsapp')}${arrow}</a></div><div class="hero-footnote">${mark}${tr('heroFootnote','span')}</div></div><div class="store-hero-image"><img src="${heroCut.image}" srcset="${heroCut.image.replace('.webp','-small.webp')} 480w, ${heroCut.image} 960w" sizes="(max-width:760px) 100vw, 55vw" width="960" height="960" alt="${esc(heroCut.name.ka)}" data-hero-image fetchpriority="high"><span class="hero-photo-brand" aria-hidden="true">MeatCO</span><button type="button" class="hero-product-tag" data-order="beef" data-cut="beef-tenderloin"><span><span class="hero-product-name">${esc(heroCut.name.ka)}</span><strong>60 ₾ <span data-i18n="heroUnit">${esc(t('heroUnit'))}</span></strong></span><span class="tag-arrow" aria-hidden="true">↗</span></button></div></section>`+categoryNav()+`<section class="container section shop-selection" id="catalog"><div class="section-heading"><div>${tr('selectionEyebrow','p','class="eyebrow"')}${tr('selectionTitle','h2')}</div>${localLink('./catalog.html','allProducts','text-button')}</div><div class="meat-grid">${featured.map(id=>card(cuts.find(c=>c.id===id))).join('')}</div>${tr('priceNote','p','class="catalog-note"')}</section>`+delivery()+extras()+b2b()+faq();}
 function catalog(){return `<div class="container page-heading"><nav class="breadcrumb" aria-label="MeatCO">${localLink('./index.html','home')}<span>/</span>${tr('navCatalog')}</nav><p class="eyebrow">MeatCO · TBILISI</p>${tr('catalogPageHeading','h1')}${tr('catalogPageIntro','p')}</div><section class="container catalog-browser"><div class="catalog-tools"><div class="filter-chips catalog-tabs" role="group" data-aria="navCatalog" aria-label="${esc(t('navCatalog'))}">${['all','pork','beef','offal','other'].map((cat,i)=>`<button type="button" data-category="${cat}" aria-pressed="${i===0}">${tr(cat)}</button>`).join('')}</div><div class="catalog-search"><label class="sr-only" for="product-search" data-i18n="productSearch">${esc(t('productSearch'))}</label><input type="search" id="product-search" autocomplete="off" maxlength="100" data-placeholder="productSearch" placeholder="${esc(t('productSearch'))}"></div></div><div class="catalog-status"><p id="product-count" role="status">${esc(t('productCount').replace('{n}',cuts.length))}</p>${tr('catalogPriceHint','span')}</div><div class="meat-grid" id="product-grid">${ordered.map((c,i)=>card(c,i,i>=12)).join('')}</div><div class="catalog-more"><button type="button" id="more-products" class="button secondary">${tr('showMore')}<span aria-hidden="true">↓</span></button></div><div id="product-empty" class="product-empty" hidden>${tr('productNoResults','h2')}${tr('productNoResultsText','p')}<button type="button" class="text-button" id="reset-products">${tr('resetFilters')}${arrow}</button></div>${tr('priceNote','p','class="catalog-note"')}</section><aside class="container cut-help"><div><p class="eyebrow">MeatCO ${tr('helpsChoose')}</p>${tr('cutsHelpTitle','h2')}${tr('cutsHelpText','p')}</div>${localLink('./dishes.html','goDishes','button secondary')}</aside>`;}
 return {header,footer,home,catalog};
}

